"""Compile a Spatial plan into one recorded, auditable Blender Python script."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

from spatial_core.plan import CompilePlan


BACKEND_VERSION = "0.1.1"


@dataclass(frozen=True)
class CompiledScript:
    source: str
    source_hash: str
    plan: CompilePlan

    def request(self, command_id: str, *, session_id: str | None = None) -> dict[str, object]:
        return {
            "schemaVersion": 1,
            "commandId": command_id,
            "sessionId": session_id,
            "title": f"Spatial compile: {self.plan.scene_id}",
            "intent": f"Apply Spatial scene {self.plan.scene_id} in {self.plan.mode} mode without raw fallback",
            "sourceHash": self.source_hash,
            "representation": {
                "kind": "spatial",
                "version": "0.1",
                "sourceHash": self.plan.source_hash,
                "fallbackAllowed": False,
            },
            "actions": [
                {"action": "script.execute", "source": self.source},
                {"action": "state.refresh"},
            ],
        }


def compile_script(plan: CompilePlan) -> CompiledScript:
    payload = json.dumps(plan.to_dict(), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    source = _SCRIPT_TEMPLATE.replace("__SPATIAL_PLAN_JSON__", repr(payload))
    return CompiledScript(source, hashlib.sha256(source.encode("utf-8")).hexdigest(), plan)


_SCRIPT_TEMPLATE = r'''# Generated by Spatial Blender Backend 0.1.1. Do not hand-edit.
import bpy
import hashlib
import json
import math
import re
from mathutils import Matrix

PLAN = json.loads(__SPATIAL_PLAN_JSON__)
SCENE_ID = PLAN["sceneId"]
ASSET = PLAN.get("asset")
SOURCE_HASH = PLAN["sourceHash"]
RUNTIME_VERSION = PLAN["runtimeVersion"]
BACKEND_VERSION = PLAN["backendVersion"]
MODE = PLAN["mode"]
FORCE = bool(PLAN["force"])
TOLERANCE = 1e-6


def _name(entity_id):
    return "SP_" + re.sub(r"[^A-Za-z0-9_]+", "_", entity_id).strip("_")


def _collection(name, parent=None):
    value = bpy.data.collections.get(name)
    if value is None:
        value = bpy.data.collections.new(name)
    owner = parent or bpy.context.scene.collection
    if value.name not in {child.name for child in owner.children}:
        owner.children.link(value)
    return value


ROOT = _collection("SPATIAL_" + re.sub(r"[^A-Za-z0-9_]+", "_", SCENE_ID))
ASSEMBLIES = _collection("Assemblies", ROOT)
GEOMETRY = _collection("Geometry", ROOT)


def _managed_objects():
    result = {}
    for obj in bpy.data.objects:
        if bool(obj.get("spatial.managed")) and obj.get("spatial.scene_id") == SCENE_ID:
            entity_id = str(obj.get("spatial.entity_id") or "")
            if entity_id:
                if entity_id in result:
                    raise RuntimeError("Duplicate Spatial entity id in Blender: " + entity_id)
                result[entity_id] = obj
    return result


EXISTING = _managed_objects()
if MODE == "build" and EXISTING:
    raise RuntimeError("Spatial build mode requires no existing managed entities for scene " + SCENE_ID)


def _matrix(desired):
    rotation = Matrix(desired["rotationMatrix"]).to_4x4()
    params = desired.get("parametersMeters") or {}
    axis = params.get("axis") or params.get("normal") or "Z"
    if axis == "X":
        intrinsic = Matrix.Rotation(math.radians(90.0), 4, "Y")
    elif axis == "Y":
        intrinsic = Matrix.Rotation(math.radians(-90.0), 4, "X")
    else:
        intrinsic = Matrix.Identity(4)
    value = rotation @ intrinsic
    value.translation = desired["locationMeters"]
    return value


def _transform_record(desired):
    matrix = _matrix(desired)
    return {
        "location": [round(float(value), 9) for value in matrix.translation],
        "rotation": [[round(float(matrix[row][column]), 9) for column in range(3)] for row in range(3)],
    }


def _external_differences(obj):
    raw = obj.get("spatial.resolved_transform")
    if not raw:
        return []
    try:
        expected = json.loads(str(raw))
    except Exception:
        return [{"property": "spatial.resolved_transform", "reason": "invalid stored JSON"}]
    differences = []
    actual_location = obj.matrix_world.translation
    for index in range(3):
        if abs(float(actual_location[index]) - float(expected["location"][index])) > TOLERANCE:
            differences.append({"property": "location", "index": index, "expected": expected["location"][index], "actual": float(actual_location[index])})
    actual_rotation = obj.matrix_world.to_3x3()
    for row in range(3):
        for column in range(3):
            if abs(float(actual_rotation[row][column]) - float(expected["rotation"][row][column])) > TOLERANCE:
                differences.append({"property": "rotation", "row": row, "column": column, "expected": expected["rotation"][row][column], "actual": float(actual_rotation[row][column])})
    return differences


def _externally_dirty(obj):
    return bool(_external_differences(obj))


def _geometry_fingerprint(kind, params):
    payload = json.dumps(
        {"kind": kind, "parametersMeters": params},
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _stored_geometry_fingerprint(obj):
    stored = str(obj.get("spatial.geometry_fingerprint") or "")
    if stored:
        return stored
    # Bridge 0.3.0 scenes predate the dedicated geometry fingerprint. Derive
    # it from their durable authored parameters so the first upgraded update
    # can preserve unchanged meshes instead of performing one destructive
    # migration rebuild.
    raw = obj.get("spatial.parameters")
    kind = str(obj.get("spatial.entity_kind") or "")
    if not raw or not kind:
        return ""
    try:
        params = json.loads(str(raw))
    except Exception:
        return ""
    return _geometry_fingerprint(kind, params)


def _operator_mesh(kind, params):
    if kind == "box":
        bpy.ops.mesh.primitive_cube_add(size=1.0)
        temp = bpy.context.object
        temp.dimensions = params["size"]
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    elif kind == "sphere":
        bpy.ops.mesh.primitive_uv_sphere_add(segments=params["segments"], ring_count=params["rings"], radius=params["radius"])
        temp = bpy.context.object
    elif kind == "cylinder":
        bpy.ops.mesh.primitive_cylinder_add(vertices=params["segments"], radius=params["radius"], depth=params["length"])
        temp = bpy.context.object
    elif kind == "cone":
        bpy.ops.mesh.primitive_cone_add(vertices=params["segments"], radius1=params["radius1"], radius2=params["radius2"], depth=params["length"])
        temp = bpy.context.object
    elif kind == "plane":
        bpy.ops.mesh.primitive_plane_add(size=1.0)
        temp = bpy.context.object
        temp.dimensions = (params["size"][0], params["size"][1], 0.0)
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    elif kind == "torus":
        bpy.ops.mesh.primitive_torus_add(
            major_segments=params["major_segments"],
            minor_segments=params["minor_segments"],
            mode="MAJOR_MINOR",
            major_radius=params["major_radius"],
            minor_radius=params["minor_radius"],
        )
        temp = bpy.context.object
    else:
        raise RuntimeError("Unsupported generated primitive: " + kind)
    mesh = temp.data
    bpy.data.objects.remove(temp, do_unlink=True)
    return mesh


def _explicit_mesh(params):
    mesh = bpy.data.meshes.new("SpatialMesh")
    mesh.from_pydata(params["vertices"], [], params["faces"])
    mesh.update()
    return mesh


def _apply_shading(mesh, kind, params):
    shading = params.get("shading") or {"mode": "flat" if kind in {"box", "plane"} else "smooth"}
    mode = shading["mode"]
    for edge in mesh.edges:
        edge.use_edge_sharp = False
    if mode == "flat":
        for polygon in mesh.polygons:
            polygon.use_smooth = False
        return
    for polygon in mesh.polygons:
        polygon.use_smooth = True
    if mode == "smooth":
        return
    if mode != "smooth_by_angle":
        raise RuntimeError("Unsupported Spatial shading mode: " + str(mode))
    threshold = math.radians(float(shading["angleDegrees"]))
    edge_faces = {}
    for polygon in mesh.polygons:
        for edge_key in polygon.edge_keys:
            edge_faces.setdefault(tuple(sorted(edge_key)), []).append(polygon)
    for edge in mesh.edges:
        faces = edge_faces.get(tuple(sorted(edge.key)), [])
        edge.use_edge_sharp = len(faces) != 2 or faces[0].normal.angle(faces[1].normal) > threshold + TOLERANCE


def _replace_mesh(obj, desired):
    params = desired["parametersMeters"]
    kind = desired["kind"]
    mesh = _explicit_mesh(params) if kind == "mesh" else _operator_mesh(kind, params)
    mesh.name = _name(desired["entityId"]) + "_Mesh"
    old = obj.data
    external_materials = list(old.materials) if old is not None else []
    obj.data = mesh
    for material in external_materials:
        mesh.materials.append(material)
    if old is not None and old.users == 0:
        bpy.data.meshes.remove(old)
    _apply_shading(mesh, kind, params)
    bevel = params.get("bevel")
    modifier = obj.modifiers.get("SpatialBevel")
    if bevel:
        if modifier is None:
            modifier = obj.modifiers.new("SpatialBevel", "BEVEL")
        modifier.width = bevel["width"]
        modifier.segments = int(bevel["segments"])
    elif modifier is not None:
        obj.modifiers.remove(modifier)


def _link_only(obj, collection):
    for owner in list(obj.users_collection):
        owner.objects.unlink(obj)
    collection.objects.link(obj)


def _new_object(desired):
    geometry = desired["kind"] not in {"assembly", "radial_array", "grid_array", "linear_array", "empty"}
    initial_data = bpy.data.meshes.new(_name(desired["entityId"]) + "_InitialMesh") if geometry else None
    obj = bpy.data.objects.new(_name(desired["entityId"]), initial_data)
    _link_only(obj, GEOMETRY if geometry else ASSEMBLIES)
    if geometry:
        _replace_mesh(obj, desired)
    else:
        obj.empty_display_type = "PLAIN_AXES"
        obj.empty_display_size = 0.1
    return obj


def _write_property(obj, key, value):
    if value is None or isinstance(value, (str, int, float, bool)):
        obj[key] = value
    else:
        obj[key] = json.dumps(value, sort_keys=True, separators=(",", ":"))


def _stamp(obj, desired):
    obj["spatial.managed"] = True
    obj["spatial.scene_id"] = SCENE_ID
    obj["spatial.entity_id"] = desired["entityId"]
    obj["spatial.entity_kind"] = desired["kind"]
    obj["spatial.source_id"] = desired.get("sourceId") or desired["entityId"]
    obj["spatial.source_hash"] = SOURCE_HASH
    obj["spatial.runtime_version"] = RUNTIME_VERSION
    obj["spatial.backend_version"] = BACKEND_VERSION
    obj["spatial.fingerprint"] = desired["fingerprint"]
    if desired.get("geometryFingerprint"):
        obj["spatial.geometry_fingerprint"] = desired["geometryFingerprint"]
    else:
        obj.pop("spatial.geometry_fingerprint", None)
    obj["spatial.resolved_transform"] = json.dumps(_transform_record(desired), sort_keys=True, separators=(",", ":"))
    obj["spatial.parameters"] = json.dumps(desired.get("parametersMeters") or {}, sort_keys=True, separators=(",", ":"))
    for key, value in (desired.get("metadata") or {}).items():
        _write_property(obj, "spatial.meta." + str(key), value)


EXTERNAL_STATE = {entity_id: _external_differences(obj) for entity_id, obj in EXISTING.items()}
RESULT = {
    "created": [],
    "updated": [],
    "unchanged": [],
    "preservedExternal": [],
    "meshPreserved": [],
    "meshReplaced": [],
    "deleted": [],
}
DESIRED = {}
for operation in PLAN["operations"]:
    desired = operation.get("desired")
    if desired is not None:
        DESIRED[desired["entityId"]] = desired


def _hierarchy_order():
    result = []
    visiting = set()
    visited = set()

    def visit(entity_id):
        if entity_id in visited:
            return
        if entity_id in visiting:
            raise RuntimeError("Cyclic resolved Spatial hierarchy at " + entity_id)
        visiting.add(entity_id)
        parent_id = DESIRED[entity_id].get("parent")
        if parent_id:
            if parent_id not in DESIRED:
                raise RuntimeError("Missing resolved parent " + parent_id + " for " + entity_id)
            visit(parent_id)
        visiting.remove(entity_id)
        visited.add(entity_id)
        result.append(entity_id)

    for candidate in sorted(DESIRED):
        visit(candidate)
    return result


ORDERED_ENTITY_IDS = _hierarchy_order()

# Existing children may sort before a parent whose world transform is changing.
# Detach every managed desired entity while preserving its current world matrix so
# applying the new parent transform cannot move a child a second time. Parenting is
# restored only after every entity has its final resolved world transform.
for entity_id in ORDERED_ENTITY_IDS:
    obj = EXISTING.get(entity_id)
    if obj is None or obj.parent is None:
        continue
    world = obj.matrix_world.copy()
    obj.parent = None
    obj.matrix_world = world


for entity_id in ORDERED_ENTITY_IDS:
    desired = DESIRED[entity_id]
    obj = EXISTING.get(entity_id)
    if obj is None:
        obj = _new_object(desired)
        EXISTING[entity_id] = obj
        obj.matrix_world = _matrix(desired)
        _stamp(obj, desired)
        RESULT["created"].append(entity_id)
        continue
    old_fingerprint = str(obj.get("spatial.fingerprint") or "")
    dirty = bool(EXTERNAL_STATE.get(entity_id))
    if old_fingerprint == desired["fingerprint"]:
        obj["spatial.source_hash"] = SOURCE_HASH
        if dirty:
            obj["spatial.external_dirty"] = True
            RESULT["preservedExternal"].append(entity_id)
        else:
            RESULT["unchanged"].append(entity_id)
        continue
    if dirty and not FORCE:
        raise RuntimeError("EXTERNAL_MODIFICATION_CONFLICT: " + entity_id + " " + json.dumps(EXTERNAL_STATE.get(entity_id), sort_keys=True))
    geometry = desired["kind"] not in {"assembly", "radial_array", "grid_array", "linear_array", "empty"}
    if geometry and obj.type != "MESH":
        raise RuntimeError("Spatial entity changed between geometry and non-geometry: " + entity_id)
    if not geometry and obj.type != "EMPTY":
        raise RuntimeError("Spatial entity changed between geometry and non-geometry: " + entity_id)
    if geometry:
        desired_geometry = str(desired.get("geometryFingerprint") or "")
        if not desired_geometry or _stored_geometry_fingerprint(obj) != desired_geometry:
            _replace_mesh(obj, desired)
            RESULT["meshReplaced"].append(entity_id)
        else:
            RESULT["meshPreserved"].append(entity_id)
    obj.matrix_world = _matrix(desired)
    obj.pop("spatial.external_dirty", None)
    _stamp(obj, desired)
    RESULT["updated"].append(entity_id)

for entity_id in ORDERED_ENTITY_IDS:
    desired = DESIRED[entity_id]
    parent_id = desired.get("parent")
    obj = EXISTING[entity_id]
    world = obj.matrix_world.copy()
    obj.parent = EXISTING[parent_id] if parent_id else None
    obj.matrix_world = world

if MODE == "update":
    for entity_id, obj in list(EXISTING.items()):
        if entity_id in DESIRED:
            continue
        if EXTERNAL_STATE.get(entity_id) and not FORCE:
            raise RuntimeError("EXTERNAL_MODIFICATION_CONFLICT: stale " + entity_id + " " + json.dumps(EXTERNAL_STATE.get(entity_id), sort_keys=True))
        bpy.data.objects.remove(obj, do_unlink=True)
        RESULT["deleted"].append(entity_id)

bpy.context.scene["spatial.scene_id"] = SCENE_ID
bpy.context.scene["spatial.source_hash"] = SOURCE_HASH
bpy.context.scene["spatial.runtime_version"] = RUNTIME_VERSION
bpy.context.scene["spatial.backend_version"] = BACKEND_VERSION
if ASSET is None:
    bpy.context.scene.pop("spatial.asset", None)
else:
    bpy.context.scene["spatial.asset"] = json.dumps(ASSET, sort_keys=True, separators=(",", ":"))
for entity_id, obj in EXISTING.items():
    if entity_id in DESIRED:
        obj.pop("spatial.asset_root", None)
if ASSET is not None:
    EXISTING[ASSET["root"]]["spatial.asset_root"] = True
bpy.context.view_layer.update()
print("SPATIAL_RESULT_JSON=" + json.dumps(RESULT, sort_keys=True, separators=(",", ":")))
'''


__all__ = ["BACKEND_VERSION", "CompiledScript", "compile_script"]
