"""Backend-neutral semantic scene model for Project Spatial."""

from .errors import (
    ConstraintConflictError,
    DuplicateIdError,
    ExternalModificationConflictError,
    InvalidFrameGraphError,
    InvalidParameterError,
    SchemaError,
    SpatialError,
    SpatialModeError,
    UnknownReferenceError,
    UnresolvedPropertyError,
    UnsupportedConstraintCycleError,
    UnsupportedRelationError,
)
from .policy import AuthoringPolicy, SpatialMode
from .model import (
    Anchor,
    Assembly,
    AssetConstitution,
    Axis,
    Bevel,
    BoxSpec,
    ConeSpec,
    CylinderSpec,
    Entity,
    Frame,
    PrimitiveSpec,
    Relation,
    Scene,
    Shading,
    SphereSpec,
)
from .plan import CompileOperation, CompilePlan, ExistingEntity, build_compile_plan
from .resolve import Bounds, Derivation, ResolvedEntity, ResolvedScene

__version__ = "0.1.0"

__all__ = [
    "AuthoringPolicy",
    "Anchor",
    "Assembly",
    "AssetConstitution",
    "Axis",
    "Bevel",
    "Bounds",
    "BoxSpec",
    "CompileOperation",
    "CompilePlan",
    "ConeSpec",
    "ConstraintConflictError",
    "DuplicateIdError",
    "CylinderSpec",
    "Derivation",
    "Entity",
    "ExistingEntity",
    "ExternalModificationConflictError",
    "InvalidFrameGraphError",
    "InvalidParameterError",
    "Frame",
    "PrimitiveSpec",
    "Relation",
    "ResolvedEntity",
    "ResolvedScene",
    "Scene",
    "Shading",
    "SchemaError",
    "SpatialError",
    "SpatialMode",
    "SpatialModeError",
    "SphereSpec",
    "UnknownReferenceError",
    "UnresolvedPropertyError",
    "UnsupportedConstraintCycleError",
    "UnsupportedRelationError",
    "build_compile_plan",
]
